language: c

os:
  - linux
  - osx
branches:
  only:
    - master
compiler:
  - gcc
  - clang
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y rpm; fi
  - git clone https://github.com/dukelsky/huskylib ~/build/dukelsky/huskylib
  - git clone https://github.com/dukelsky/smapi ~/build/dukelsky/smapi
script:
  - cd  ~/build/dukelsky/huskylib
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - sudo make install
  - cd  ~/build/dukelsky/smapi
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - sudo make install
  - cd  $TRAVIS_BUILD_DIR
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - cpack
